<a href="https://colab.research.google.com/github/NSR9/PythonForML-AI-Notes/blob/master/s3pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np 
import torch

In [0]:
list = [1,2,3]
list_to_nparray = np.array(list)
list_to_torchtensor = torch.tensor(list)
nparray_to_torchtensor = torch.tensor(list_to_nparray)
nparray_to_torchtensor1 = torch.from_numpy(list_to_nparray)
nparray_from_tensor = nparray_to_torchtensor.numpy()

list_to_nparray[0] = 9


print(list)
print(list_to_nparray)
print(list_to_torchtensor)
print(nparray_to_torchtensor)
print(nparray_to_torchtensor1)
print(nparray_from_tensor)

[1, 2, 3]
[9 2 3]
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([9, 2, 3])
[1 2 3]


In [0]:
tens1 = torch.ones(2,3,dtype = torch.float16)
npry = tens1.numpy()
#npry[:] *= 0.5
print(npry)
num = npry
num = num*0.5

print(num)

print(tens1)
print(npry)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
[[1. 1. 1.]
 [1. 1. 1.]]


In [0]:
a = torch.zeros(3, 2)
b = torch.ones(3, 2)
print(torch.cat((a, b), dim=1))
c = torch.cat((a,b),dim=0)
print(c)

tensor([[0., 0., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [0]:

tensor = torch.rand((5, 3))
rows = torch.tensor([0,1])
print(tensor)
tensor[rows]

tensor([[0.1949, 0.0753, 0.0317],
        [0.6879, 0.5928, 0.3901],
        [0.1948, 0.1874, 0.1114],
        [0.8628, 0.3791, 0.0076],
        [0.5921, 0.3740, 0.0684]])


tensor([[[0.1949, 0.0753, 0.0317],
         [0.6879, 0.5928, 0.3901]]])

In [0]:
tensor = torch.rand((2,3,4))
tensor1 = tensor.reshape(24)
tensor2 = tensor.view((3,2,4))
print(tensor)
print(tensor1)
print(tensor2)

tensor([[[0.6738, 0.4217, 0.3125, 0.4527],
         [0.0152, 0.8959, 0.2827, 0.5541],
         [0.4097, 0.8975, 0.7173, 0.0856]],

        [[0.7245, 0.5336, 0.1718, 0.8047],
         [0.4135, 0.9154, 0.6965, 0.2036],
         [0.8579, 0.8143, 0.2989, 0.3272]]])
tensor([0.6738, 0.4217, 0.3125, 0.4527, 0.0152, 0.8959, 0.2827, 0.5541, 0.4097,
        0.8975, 0.7173, 0.0856, 0.7245, 0.5336, 0.1718, 0.8047, 0.4135, 0.9154,
        0.6965, 0.2036, 0.8579, 0.8143, 0.2989, 0.3272])
tensor([[[0.6738, 0.4217, 0.3125, 0.4527],
         [0.0152, 0.8959, 0.2827, 0.5541]],

        [[0.4097, 0.8975, 0.7173, 0.0856],
         [0.7245, 0.5336, 0.1718, 0.8047]],

        [[0.4135, 0.9154, 0.6965, 0.2036],
         [0.8579, 0.8143, 0.2989, 0.3272]]])


In [0]:
b = torch.tensor([[2,1]])

a = torch.tensor([[1,2,3],[1,2,3]])
print(a)
print(b) 
a = a.reshape(-1,2)
b = b.view(2,-1)
print(a)
print(b)

dot = torch.mm(a,b)
print(dot)
sum = torch.sum(dot)
print(sum)

tensor([[1, 2, 3],
        [1, 2, 3]])
tensor([[2, 1]])
tensor([[1, 2],
        [3, 1],
        [2, 3]])
tensor([[2],
        [1]])
tensor([[4],
        [7],
        [7]])
tensor(18)
